/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package updatedloginfunctionality;

import com.formdev.flatlaf.FlatIntelliJLaf;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ikhmal Fakhri <u2000600@siswa.um.edu.my>
 */
public class adminPanel extends javax.swing.JFrame {

    Connection con = ConnectDatabase.connectdb();
    PreparedStatement ps = null;
    ResultSet rs = null;

    public adminPanel() {
        initComponents();
        txtSpec2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Edit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addBttn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSpec2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtSpec1 = new javax.swing.JComboBox<>();
        txtCredit = new javax.swing.JSpinner();
        txtMuet = new javax.swing.JSpinner();
        txtOcc = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel12.setText("Which Department");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 2147483647));
        setPreferredSize(new java.awt.Dimension(1200, 618));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Edit.setText("View");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 433, 105, 50));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("Credit Hour (s)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 162, 148, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD MODULE COURSE INFORMATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 44, 394, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Course Code");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 121, 120, -1));

        txtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LECTURE", "TUTORIAL", "LAB", "LECTURE, TUTORIAL, LAB", "LECTURE, TUTORIAL", "TUTORIAL, LAB" }));
        getContentPane().add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 202, 228, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setText("Select Activity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 202, 148, -1));

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 121, 228, -1));

        Exit.setText("Back");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 8, -1, 30));

        jButton1.setText("Delete");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 433, 105, 50));

        addBttn.setText("Add New");
        addBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBttnActionPerformed(evt);
            }
        });
        getContentPane().add(addBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 433, 105, 50));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel9.setText("MUET Requirement");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setText("Specialization");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 320, 148, -1));

        txtSpec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpec2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSpec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 360, 228, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 382, 303, -1));

        txtSpec1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "COMPUTER SCIENCE", "INFORMATION TECHNOLOGY" }));
        txtSpec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpec1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSpec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 320, 228, -1));

        txtCredit.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(txtCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 162, 228, -1));

        txtMuet.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));
        getContentPane().add(txtMuet, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 280, 228, -1));

        txtOcc.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        getContentPane().add(txtOcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 240, 228, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("No. of Occurrences");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 240, 148, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Module Code", "credit", "activity", "occ", "muet", "degree", "dept.", "lecturer", "day", "start_time", "end_time"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 650, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        adminModules db = new adminModules();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        WelcomePageV2 wp2 = new WelcomePageV2();
        wp2.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_ExitActionPerformed

    private void addBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBttnActionPerformed
        
            String coursecode = txtCode.getText().toUpperCase();
            String type = txtType.getSelectedItem().toString();
            int credit = (int) txtCredit.getValue();
            int muet = (int) txtMuet.getValue();
            int occ = (int) txtOcc.getValue();
            String spc1 = txtSpec1.getSelectedItem().toString();
            String spc2;
            int csit = -1;
            int stype = -1; //to check for errors
            if (spc1.equals("COMPUTER SCIENCE")) {
                csit = 1;
            } else if (spc1.equals("ALL")) {
                csit = 0;
            } else {
                csit = 2;
            }

//        if(spc2.equals("ALL")){
//            stype = 0;
            if (csit == 1 || csit == 2) {
                spc2 = txtSpec2.getSelectedItem().toString();
                if (spc2.equals("Artificial Intelligence")) {
                    stype = 2;
                } else if (spc2.equals("Information Systems")) {
                    stype = 3;
                } else if (spc2.equals("Computer System and Network")) {
                    stype = 1;
                } else if (spc2.equals("Multimedia")) {
                    stype = 6;
                } else if (spc2.equals("Data Science")) {
                    stype = 5;
                } else if (spc2.equals("Software Engineering")) {
                    stype = 4;
                }
            } else {
                stype = 0;
            }

            try {
                /* inserting directly to VALID_MODULES
    Class.forName("org.apache.derby.jdbc.ClientDriver");
    Connection con = (Connection) DriverManager.getConnection("jdbc:derby://localhost:1527/userlogin", "app", "app");
    Statement st;
    st = con.createStatement();
    
    String strQuery3 = "SELECT COUNT(*) FROM app.valid_modules where module='" + coursecode + "'";
    ResultSet rs3 = st.executeQuery(strQuery3);
    rs3.next();
    String Countrow3 = rs3.getString(1);
    System.out.println(Countrow3);
    if (Countrow3.equals("0")) {
    int i = st.executeUpdate("INSERT INTO APP.VALID_MODULES(MODULE,ACTIVITY,CREDIT,MUET,CSIT,STUDENTTYPE,OCC)VALUES('" + coursecode + "','" + type + "',"+credit+","+muet+","+csit+","+stype+","+occ+")");
    JOptionPane.showMessageDialog(this, "Course Added");
    } else {
    JOptionPane.showMessageDialog(this, "Added course already exists!");
    }
    
    // }
    //}
                 */ int occCount = 1;

//            String q1 = "INSERT INTO app.new_modules (MODULE_CODE, CREDIT, ACTIVITY, OCC, MUET, CSIT, STUDENT_TYPE) VALUES ('" + coursecode + "', " + credit + ", '"+type+"',"+occCount+","+muet+","+csit+","+stype+") ";
//            ps = con.prepareStatement(q1);
                while (occCount <= occ) {
                    String q1 = "INSERT INTO app.new_modules (MODULE_CODE, CREDIT, ACTIVITY, OCC, MUET, CSIT, STUDENT_TYPE) VALUES ('" + coursecode + "', " + credit + ", '" + type + "'," + occCount + "," + muet + "," + csit + "," + stype + ") ";
                    ps = con.prepareStatement(q1);
                    ps.executeUpdate();
                    occCount++;
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Failed to Add Course" + credit + muet + csit + stype);
            }

//displaying newly added modules
        try{
            String q2 = "SELECT * FROM new_modules";
            ps = con.prepareStatement(q2);
            rs = ps.executeQuery();
            while (rs.next()) {
                String MODULES = rs.getString("MODULE_CODE");
                String CREDIT = rs.getString("CREDIT");
                String ACTIVITY = rs.getString("ACTIVITY");
                String OCC = Integer.toString(rs.getInt("OCC"));
                String MUET = Integer.toString(rs.getInt("MUET"));
                String CSIT = Integer.toString(rs.getInt("CSIT"));
                String STYPE = Integer.toString(rs.getInt("STUDENT_TYPE"));
                

                String tbData[] = {MODULES, CREDIT, ACTIVITY, OCC, MUET, CSIT, STYPE};
                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();

                tblModel.addRow(tbData);
            }

        } catch (SQLException ex) {
            Logger.getLogger(adminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_addBttnActionPerformed

    private void txtSpec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpec1ActionPerformed
        // TODO add your handling code here:
        if (txtSpec1.getSelectedItem().toString().equals("COMPUTER SCIENCE")) {
            txtSpec2.setVisible(true);
            txtSpec2.addItem("Artificial Intelligence");
            txtSpec2.addItem("Information Systems");
            txtSpec2.addItem("Software Engineering");
            txtSpec2.addItem("Computer System and Network");
            txtSpec2.addItem("Data Science");
            txtSpec2.removeItem("Multimedia");
        } else if (txtSpec1.getSelectedItem().toString().equals("INFORMATION TECHNOLOGY")) {
            txtSpec2.setVisible(true);
            txtSpec2.removeAllItems();
            txtSpec2.addItem("Multimedia");
        } else {
            txtSpec2.setVisible(false);
        }
    }//GEN-LAST:event_txtSpec1ActionPerformed

    private void txtSpec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpec2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpec2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton Exit;
    private javax.swing.JButton addBttn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCode;
    private javax.swing.JSpinner txtCredit;
    private javax.swing.JSpinner txtMuet;
    private javax.swing.JSpinner txtOcc;
    private javax.swing.JComboBox<String> txtSpec1;
    private javax.swing.JComboBox<String> txtSpec2;
    private javax.swing.JComboBox<String> txtType;
    // End of variables declaration//GEN-END:variables
}
