/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package updatedloginfunctionality;

import java.awt.CardLayout;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;

/**
 *
 * @author T_T
 */
//to pop up after staff clicks "register" in staff welcome page
public class StaffRegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form StaffRegisterForm
     */
    Connection con;
    PreparedStatement ps = null;
    ResultSet rs = null;
    CardLayout cardLayout2;
    public StaffRegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffRegisterCard = new javax.swing.JPanel();
        registerPanel2 = new javax.swing.JPanel();
        exit1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fullNameField1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        passwordRegisterField1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        departmentLabel = new javax.swing.JLabel();
        registerStaffBttn = new javax.swing.JButton();
        departmentMenu = new javax.swing.JComboBox<>();
        staffIdField = new javax.swing.JTextField();
        departmentLabel1 = new javax.swing.JLabel();
        departmentMenu1 = new javax.swing.JComboBox<>();
        messagePanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emptyFieldLabel1 = new javax.swing.JLabel();
        registerSuccessLabel1 = new javax.swing.JLabel();
        duplicateStaffIdLabel = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffRegisterCard.setPreferredSize(new java.awt.Dimension(1366, 783));
        StaffRegisterCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPanel2.setBackground(new java.awt.Color(58, 83, 155));
        registerPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 247, 252), 2));
        registerPanel2.setPreferredSize(new java.awt.Dimension(420, 540));

        exit1.setBackground(new java.awt.Color(80, 101, 177));
        exit1.setFont(new java.awt.Font("Readex Pro Medium", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(244, 247, 252));
        exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit1.setText("X");
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(80, 101, 177));
        jLabel8.setFont(new java.awt.Font("Readex Pro Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(244, 247, 252));
        jLabel8.setText("FULL NAME :");

        fullNameField1.setBackground(new java.awt.Color(58, 83, 155));
        fullNameField1.setFont(new java.awt.Font("Readex Pro Light", 0, 18)); // NOI18N
        fullNameField1.setForeground(new java.awt.Color(244, 247, 252));
        fullNameField1.setBorder(null);

        jSeparator6.setForeground(new java.awt.Color(244, 247, 252));

        jLabel9.setBackground(new java.awt.Color(80, 101, 177));
        jLabel9.setFont(new java.awt.Font("Readex Pro Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(244, 247, 252));
        jLabel9.setText("PASSWORD :");

        jSeparator7.setForeground(new java.awt.Color(244, 247, 252));

        passwordRegisterField1.setBackground(new java.awt.Color(58, 83, 155));
        passwordRegisterField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordRegisterField1.setForeground(new java.awt.Color(244, 247, 252));
        passwordRegisterField1.setBorder(null);

        jLabel10.setBackground(new java.awt.Color(80, 101, 177));
        jLabel10.setFont(new java.awt.Font("Readex Pro Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(244, 247, 252));
        jLabel10.setText("STAFF ID :");

        jSeparator8.setForeground(new java.awt.Color(244, 247, 252));

        departmentLabel.setBackground(new java.awt.Color(80, 101, 177));
        departmentLabel.setFont(new java.awt.Font("Readex Pro Medium", 0, 18)); // NOI18N
        departmentLabel.setForeground(new java.awt.Color(244, 247, 252));
        departmentLabel.setText("DEPARTMENT :");
        departmentLabel.setToolTipText("");

        registerStaffBttn.setBackground(new java.awt.Color(80, 101, 177));
        registerStaffBttn.setFont(new java.awt.Font("Readex Pro Medium", 0, 14)); // NOI18N
        registerStaffBttn.setForeground(new java.awt.Color(244, 247, 252));
        registerStaffBttn.setText("REGISTER");
        registerStaffBttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 247, 252)));
        registerStaffBttn.setContentAreaFilled(false);
        registerStaffBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerStaffBttn.setFocusPainted(false);
        registerStaffBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerStaffBttnMouseClicked(evt);
            }
        });
        registerStaffBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStaffBttnActionPerformed(evt);
            }
        });

        departmentMenu.setBackground(new java.awt.Color(244, 247, 252));
        departmentMenu.setFont(new java.awt.Font("Readex Pro Medium", 0, 14)); // NOI18N
        departmentMenu.setForeground(new java.awt.Color(58, 83, 155));
        departmentMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSN", "AI", "IS", "SE", "DS", "MM" }));
        departmentMenu.setBorder(null);
        departmentMenu.setName("box"); // NOI18N

        staffIdField.setBackground(new java.awt.Color(58, 83, 155));
        staffIdField.setFont(new java.awt.Font("Readex Pro Light", 0, 18)); // NOI18N
        staffIdField.setForeground(new java.awt.Color(244, 247, 252));
        staffIdField.setBorder(null);

        departmentLabel1.setBackground(new java.awt.Color(80, 101, 177));
        departmentLabel1.setFont(new java.awt.Font("Readex Pro Medium", 0, 18)); // NOI18N
        departmentLabel1.setForeground(new java.awt.Color(244, 247, 252));
        departmentLabel1.setText("CS_IT :");
        departmentLabel1.setToolTipText("");

        departmentMenu1.setBackground(new java.awt.Color(244, 247, 252));
        departmentMenu1.setFont(new java.awt.Font("Readex Pro Medium", 0, 14)); // NOI18N
        departmentMenu1.setForeground(new java.awt.Color(58, 83, 155));
        departmentMenu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Information Technology" }));
        departmentMenu1.setBorder(null);
        departmentMenu1.setName("box"); // NOI18N

        javax.swing.GroupLayout registerPanel2Layout = new javax.swing.GroupLayout(registerPanel2);
        registerPanel2.setLayout(registerPanel2Layout);
        registerPanel2Layout.setHorizontalGroup(
            registerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(registerPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(registerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registerStaffBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator8)
                            .addGroup(registerPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(registerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordRegisterField1)
                                    .addGroup(registerPanel2Layout.createSequentialGroup()
                                        .addComponent(fullNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(staffIdField))
                        .addComponent(departmentLabel1)
                        .addComponent(departmentLabel)
                        .addGroup(registerPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(registerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(departmentMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(departmentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        registerPanel2Layout.setVerticalGroup(
            registerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit1)
                .addGap(160, 160, 160)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(fullNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(staffIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(passwordRegisterField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(departmentLabel1)
                .addGap(18, 18, 18)
                .addComponent(departmentMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(departmentLabel)
                .addGap(18, 18, 18)
                .addComponent(departmentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(registerStaffBttn)
                .addGap(70, 70, 70))
        );

        StaffRegisterCard.add(registerPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 690, 783));

        messagePanel2.setBackground(new java.awt.Color(244, 247, 252));
        messagePanel2.setPreferredSize(new java.awt.Dimension(420, 540));

        jLabel11.setBackground(new java.awt.Color(96, 111, 137));
        jLabel11.setFont(new java.awt.Font("Readex Pro Medium", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(96, 111, 137));
        jLabel11.setText("for more information");

        jLabel12.setBackground(new java.awt.Color(80, 101, 177));
        jLabel12.setFont(new java.awt.Font("Readex Pro Medium", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(58, 83, 155));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText(" Register Your Details");

        jLabel13.setBackground(new java.awt.Color(96, 111, 137));
        jLabel13.setFont(new java.awt.Font("Readex Pro Medium", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(96, 111, 137));
        jLabel13.setText("Tip: Some labels can be hovered over");

        emptyFieldLabel1.setBackground(new java.awt.Color(96, 111, 137));
        emptyFieldLabel1.setFont(new java.awt.Font("Readex Pro Medium", 0, 14)); // NOI18N
        emptyFieldLabel1.setForeground(new java.awt.Color(145, 38, 67));
        emptyFieldLabel1.setText("All fields must be filled for registration");

        registerSuccessLabel1.setBackground(new java.awt.Color(96, 111, 137));
        registerSuccessLabel1.setFont(new java.awt.Font("Readex Pro Medium", 0, 14)); // NOI18N
        registerSuccessLabel1.setForeground(new java.awt.Color(58, 83, 155));
        registerSuccessLabel1.setText("You've successfully registered!");

        duplicateStaffIdLabel.setBackground(new java.awt.Color(96, 111, 137));
        duplicateStaffIdLabel.setFont(new java.awt.Font("Readex Pro Medium", 0, 14)); // NOI18N
        duplicateStaffIdLabel.setForeground(new java.awt.Color(145, 38, 67));
        duplicateStaffIdLabel.setText("The entered staff id has already been registered");

        jSeparator9.setForeground(new java.awt.Color(58, 83, 155));

        javax.swing.GroupLayout messagePanel2Layout = new javax.swing.GroupLayout(messagePanel2);
        messagePanel2.setLayout(messagePanel2Layout);
        messagePanel2Layout.setHorizontalGroup(
            messagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanel2Layout.createSequentialGroup()
                .addGroup(messagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messagePanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(messagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(messagePanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel11))
                            .addComponent(jLabel13)
                            .addComponent(registerSuccessLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duplicateStaffIdLabel)
                            .addComponent(emptyFieldLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(messagePanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(messagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        messagePanel2Layout.setVerticalGroup(
            messagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(121, 121, 121)
                .addComponent(emptyFieldLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duplicateStaffIdLabel)
                .addGap(18, 18, 18)
                .addComponent(registerSuccessLabel1)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        StaffRegisterCard.add(messagePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 683, 783));

        getContentPane().add(StaffRegisterCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit1MouseClicked

    private void registerStaffBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerStaffBttnMouseClicked
        try {
            // TODO add your handling code here:
            String q1 = "SELECT staff_id FROM stafflogin where staff_id = '" + staffIdField.getText().toLowerCase() + "'";
            ps = con.prepareStatement(q1);
            rs = ps.executeQuery();

            if (fullNameField1.getText().trim().length() == 0
                || String.valueOf(passwordRegisterField1.getPassword()).trim().length() == 0
                || staffIdField.getText().trim().length() == 0) {
                emptyFieldLabel1.setVisible(true);

            } else if (rs.next()) {
                emptyFieldLabel1.setVisible(false);
                duplicateStaffIdLabel.setVisible(true);

            } else {

                String q2 = "INSERT INTO stafflogin values (?, ?, ?, ?)";

                String fullNameStaff = fullNameField1.getText();
                String passwordStaff = String.valueOf(passwordRegisterField1.getPassword());
                String staffId = staffIdField.getText();
                String department = departmentMenu.getSelectedItem().toString();

                int departmentNum = switch (department) {
                    case "CSN" ->
                    1;
                    case "AI" ->
                    2;
                    case "IS" ->
                    3;
                    case "SE" ->
                    4;
                    case "DS" ->
                    5;
                    case "MM" ->
                    6;
                    default ->
                    0;
                };

                ps = con.prepareStatement(q2);
                ps.setString(1, staffId);
                ps.setString(2, fullNameStaff);
                ps.setString(3, passwordStaff);
                ps.setInt(4, departmentNum);
                ps.executeUpdate();

                emptyFieldLabel1.setVisible(false);
                duplicateStaffIdLabel.setVisible(false);
                registerSuccessLabel1.setVisible(true);
            }

        } catch (SQLException ex) {
        }

    }//GEN-LAST:event_registerStaffBttnMouseClicked

    private void registerStaffBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStaffBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerStaffBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffRegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StaffRegisterCard;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel departmentLabel1;
    private javax.swing.JComboBox<String> departmentMenu;
    private javax.swing.JComboBox<String> departmentMenu1;
    private javax.swing.JLabel duplicateStaffIdLabel;
    private javax.swing.JLabel emptyFieldLabel1;
    private javax.swing.JLabel exit1;
    private javax.swing.JTextField fullNameField1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel messagePanel2;
    private javax.swing.JPasswordField passwordRegisterField1;
    private javax.swing.JPanel registerPanel2;
    private javax.swing.JButton registerStaffBttn;
    private javax.swing.JLabel registerSuccessLabel1;
    private javax.swing.JTextField staffIdField;
    // End of variables declaration//GEN-END:variables
}
